---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

# update modules
  - package-ecosystem: "maven"
    directory: "/prometheus-demo-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "maven"
    directory: "/prometheus-eureka-server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
 
